homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml 
  packages: !include_dir_named packages
# Show # Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 172.30.0.0/16
    - 172.18.0.0/16
    - 192.168.1.1
  cors_allowed_origins:
    - !secret baseurl
    - http://192.168.1.121:8123
    - http://loftpi:8123
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.51/32
    - 172.30.0.0/16
    - 172.18.0.0/16
#auth_providers:
#    - type: trusted_networks
#      trusted_networks:
#        - 127.0.0.1
#        - ::1
#        - 192.168.1.51/32
#        - 172.30.0.0/16
#        - 172.18.0.0/16
#      allow_bypass_login: true
#    - type: homeassistant
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
#history:

# View all events in a logbook
#logbook:

# Enables a map showing the location of tracked devices
#map:

# Track the sun
#sun:

# Weather prediction
#sensor:
#  - platform: yr

# Text to speech
#tts:
#  - platform: google

group: !include groups.yaml
script: !include scripts.yaml
