
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_logitude
  # Impacts weather/sunrise data
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  packages: !include_dir_named packages
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password
  trusted_networks: #networks not requiring password
    - 127.0.0.1
    - ::1
# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor yr:
  platform: yr

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

tradfri:
  host: !secret tradfri_host
  api_key: !secret tradfri_api_key

notify:  !include_dir_merge_list notify/

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg
  run_test: true

device_tracker: !include device_tracker.yaml
camera: !include_dir_merge_list camera/
media_player: !include media_players.yaml
automation: !include_dir_merge_list automation
sensor: !include_dir_merge_list sensor/
binary_sensor: !include_dir_merge_list binary_sensor/
switch: !include_dir_merge_list switch/
input_select: !include_dir_merge_named input_select/
# Web Links #
weblink: !include web_links.yaml
shell_command: !include_dir_merge_named shell_commands/
group: !include_dir_merge_named group/
logger: !include logger.yaml


