resources:
  - url: /local/custom_ui/weather-card.js
    type: js
  - url: /local/custom_ui/clock-element.js
    type: js
  - url: /local/custom_ui/circle-sensor-card.js
    type: module
  - url: /local/custom_ui/dark-sky-weather-card.js?v=1
    type: js
  - url: /local/custom-lovelace/monster-card/monster-card.js?v=1
    type: js
  - url: /local/custom-lovelace/gauge-card/gauge-card.js
    type: js
  - url: /local/custom-lovelace/bignumber-card/bignumber-card.js
    type: js
  - url: /local/custom_ui/alarm_control_panel-card.js?v=1.1
    type: js
  - url: /local/surveillance-card/surveillance-card.js?v=0.1
    type: module
  - url: /local/custom-lovelace/thermostat-card/thermostat-card.js?v=1.3
    type: module
  - url: /local/custom_ui/canvas-gauge-card.js?v=0.1
    type: module
  - url: /local/custom_ui/calendar-card.js
    type: module
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /local/custom_ui/ext-weblink.js?v=0.6
    type: js
  - url: /local/custom_ui/slider-entity-row.js?v=0.2
    type: js
  - url: /local/custom-lovelace/group-card/group-card.js?v=1.0
    type: js
  - url: /local/custom_ui/button-card.js
    type: module
  - url: /local/lovelace-fullykiosk/lovelace-fullykiosk.js?v=1
    type: js
  - url: /local//lovelace-fullykiosk/lovelace-fullykiosk-config.js?v=2
    type: js
  - url: /local/lovelace-player/lovelace-player.js?v=1
    type: js
  - url: /local/lovelace-player/lovelace-player-config.js?v=2
    type: js
title: My Home
views:
  - icon: mdi:home-assistant
    id: home
    # Name of the view. Will be used as the tooltip for tab icon
    title: Home
    # theme: darkorange
    cards:
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - light.master_bedroom
      - type: custom:monster-card
        card:
          type: entities
          title: Loft
          show_header_toggle: false
        filter:
          include:
            - entity_id: '*loft*'
      - type: entities
        title: heating
        show_header_toggle: false
        entities:
            - switch.immersion_heater
      - type: entities
        title: weatherstation
        show_header_toggle: false
        entities:
           - sensor.inside_temperature
           - sensor.inside_humidity
           - sensor.average_wind_speed
           - sensor.outside_temperature
           - sensor.outside_humidity
           - sensor.wind_gust_speed
           - sensor.relative_pressure
  - icon: mdi:security
    id: security
    title: Security
    cards:
      - type: entities
        title: Home Security
        show_header_toggle: false
        entities:
          - alarm_control_panel.ha_alarm
      - type: entities
        title: Doors
        show_header_toggle: false
        entities:
          - binary_sensor.back_door
          - binary_sensor.front_door
      - type: glance
        title: People
        show_header_toggle: false
        entities:
          - device_tracker.matt_presence
          - device_tracker.nat_presence
          - device_tracker.evie_presence

      - type: horizontal-stack
        cards:
          - type: custom:alarm_control_panel-card
            entity: alarm_control_panel.ha_alarm
            title: HA Alarm
            states:
              - arm_home
              - arm_away
  - icon: mdi:weather-cloudy
    id: weather
    title: Weather
    cards:
      - type: entities
        title: Weather
        entities:
          - sensor.dark_sky_cloud_coverage
          - sensor.dark_sky_hourly_summary
          - sensor.dark_sky_daily_summary
      - type: entities
        title: Forecast
        entities:
          - sensor.forecast_0
          - sensor.forecast_1
          - sensor.forecast_2
          - sensor.forecast_3
          - sensor.forecast_4
          - sensor.forecast_5
          - sensor.forecast_6
          - sensor.forecast_7
      - type: iframe
        aspect_ratio: 70%
        url: https://embed.windy.com/embed2.html?rain,51.291,-1.057,6
  - icon: mdi:home
    id: outside
    title: Outside
    cards:
      - type: custom:monster-card
        card:
          type: entities
          title: Shed
          show_header_toggle: false
        filter:
          include:
            - entity_id: '*shed*'
      - type: custom:monster-card
        card:
          type: entities
          title: Greenhouse
          show_header_toggle: false
        filter:
          include:
            - entity_id: '*greenhouse*'

  - icon: mdi:home
    id: groundfloor
    title: Ground Floor
    cards:
      - type: custom:monster-card
        card:
          type: entities
          title: Livingroom
          show_header_toggle: false
        filter:
          include:
            - entity_id: '*living*'
      - type: custom:monster-card
        card:
          type: entities
          title: Kitchen
          show_header_toggle: false
        filter:
          include:
            - entity_id: '*kitchen*'
      - type: custom:monster-card
        card:
          type: entities
          title: Utility room
          show_header_toggle: false
        filter:
          include:
            - entity_id: '*utility*'
  - icon: mdi:home
    id: firstfloor
    title: First Floor
    cards:
      - type: custom:monster-card
        card:
          type: entities
          title: Bathroom
          show_header_toggle: false
        filter:
          include:
            - entity_id: '*bathroom*'
      - type: custom:monster-card
        card:
          type: entities
          title: Masterbed
          show_header_toggle: false
        filter:
          include:
            - entity_id: '*masterbed*'
      - type: custom:monster-card
        card:
          type: entities
          title: Little Bedroom
          show_header_toggle: false
        filter:
          include:
            - entity_id: '*littlebed*'
      - type: custom:monster-card
        card:
          type: entities
          title: Guest Bedroom
          show_header_toggle: false
        filter:
          include:
            - entity_id: '*guestbed*'
  - title: Surveillance
    id: surveillance
    icon: mdi:cctv
    panel: true
    cards:
      - type: custom:surveillance-card
        thumb_interval: 15
        update_interval: 2
        cameras:
          - entity: camera.baby
            motion_entity: binary_sensor.littlebed_motion
  - icon: mdi:play-circle-outline
    id: media
    title: Media
    cards:
      - type: custom:monster-card
        card:
          type: entities
          title: Media Players
        filter:
          include:
            - domain: media_player
  - icon: mdi:settings
    id: settings
    title: Settings
    cards:
      - type: entities
        title: HASS Details
        show_header_toggle: false
        entities:
          - switch.developer_mode
          - sensor.hassuptime
          - entity: sensor.current_version
            secondary_info: last-changed
          - sensor.ssl_certificate_expiry
          - input_select.current_theme
      - type: entities
        title: Network Details
        show_header_toggle: false
        entities:
           - sensor.dns_queries_today
           - sensor.domains_being_blocked
           - sensor.ads_blocked_today
           - sensor.ads_percentage_today
           - sensor.unique_domains
           - sensor.queries_forwarded
           - sensor.queries_cached
           - switch.pihole
           - switch.set_pihole_pass
           - entity: sensor.speedtest_download
             secondary_info: last-changed
           - sensor.speedtest_upload
           - sensor.speedtest_ping
           
  - icon: mdi:test-tube
    id: test
    title: Testing
    cards:
      - type: glance
        title: Devices
        entities:
          - entity: device_tracker.matt_matt
            title: Owntracks
          - entity: device_tracker.matt_presence
            title: "AppDaemon Matt"
          - entity: device_tracker.repeater_matt_phone
            title: "Matt Phone Repeater"
          - entity: device_tracker.nat_nat
            title: Owntracks
          - entity: device_tracker.nat_presence
            title: "AppDaemon Nat"
          - entity: device_tracker.repeater_nat_phone
            title: "Nat Phone Repeater"
      - type: map
        entities:
          - entity: device_tracker.matt_matt
          - entity: device_tracker.nat_nat
          - zone.home
      - type: custom:monster-card
        card:
          type: entities
          title: Things that are probably broken
        filter:
          include:
            - state: "unknown"
  - icon: mdi:android
    id: android
    title: Android
    cards:
      - type: entities
        title: Fire
        show_header_toggle: false
        entities:
          - light.fire_dashboard_screen
          - binary_sensor.fire_dashboard_motion
          - media_player.fire_dashboard
