binary_sensor:
- platform: bayesian
  prior: 0.2
  name: 'Matt Presence'
  probability_threshold: 0.5
  observations:
    - entity_id: 'device_tracker.matt_matt'
      prob_given_true: 0.7
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.repeater_matt_phone'
      prob_given_true: 0.7
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
