binary_sensor:
- platform: bayesian
  prior: 0.5
  name: 'Nat Presence'
  probability_threshold: 0.5
  observations:
    - entity_id: 'device_tracker.nat_nat'
      prob_given_true: 0.7
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.repeater_nat_phone'
      prob_given_true: 0.7
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'