###############################################################################
#   @author         :   Matthew Hilton
#   @date           :   12/03/2018
#   @package        :   Home Assistant
#   @description    :   Masterbed
###############################################################################
homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'masterbed'

      exposed: &exposed
        <<: *customize
        emulated_hue: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

    group.masterbed:
      <<: *customize
      friendly_name: "Master bedroom"
    light.masterbed_lights:
      <<: *customize
      friendly_name: "Master bedroom Lights"
      icon: mdi:lightbulb
    group.masterbed_switches:
      <<: *customize
      friendly_name: "Master bedroom Switches"
    sensor.masterbed_temperature:
      <<: *customize
      friendly_name: "Master bedroom Temperature"
      icon: mdi:thermometer-lines
      unit_of_measurement: '°C'
    sensor.masterbed_humidity:
      <<: *customize
      friendly_name: "Master bedroom Humidity"
      unit_of_measurement: '%'
    binary_sensor.masterbed_occupancy:
      <<: *customize
      friendly_name: "Master bedroom Occupancy"
    binary_sensor.masterbed_door:
      <<: *customize
      friendly_name: "Master bedroom Door"
    binary_sensor.masterbed_window:
      <<: *customize
      friendly_name: "Master bedroom Window"
    switch.masterbed_switch:
      <<: *customize
      friendly_name: "Master bedroom Switch"
    light.masterbed_light:
      <<: *customize
      friendly_name: "Master bedroom Light"

group:
  masterbed:
    control: hidden
    entities:
      - sensor.masterbed_temperature
      - sensor.masterbed_humidity
      - binary_sensor.masterbed_occupancy
      - binary_sensor.masterbed_door
      - binary_sensor.masterbed_window
      - group.masterbed_switches
      - light.masterbed_lights
  masterbed_switches:
    entities:
      - switch.masterbed_switch
sensor:
  - platform: template
    sensors:
      masterbed_temperature:
        value_template: '{{states.sensor.template.state}}'
      masterbed_humidity:
        value_template: '{{states.sensor.template.state}}'

binary_sensor:
  - platform: template
    sensors:
      masterbed_occupancy:
        value_template: "{{ is_state('binary_sensor.template', 'on')}}"
        device_class: occupancy
      masterbed_door:
        value_template: "{{ is_state('binary_sensor.template', 'on')}}"
        device_class: door
      masterbed_window:
        value_template: "{{ is_state('binary_sensor.template', 'on')}}"
        device_class: window

switch:
  - platform: template
    switches:
      masterbed_switch:
        value_template: "{{ is_state('switch.template', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.template
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.template

light:
  - platform: template
    lights:
      masterbed_light:
        value_template: "{{ is_state('light.template', 'on') }}"
        turn_on:
          service: light.turn_on
          data:
            entity_id: light.template
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.template
  - platform: group
    name: masterbed lights
    entities:
      - light.masterbed_light