###############################################################################
#   @author         :   Matthew Hilton
#   @date           :   12/03/2018
#   @package        :   Home Assistant
#   @description    :   Toilet
###############################################################################
homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'toilet'

      exposed: &exposed
        <<: *customize
        emulated_hue: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

    group.toilet:
      <<: *customize
      friendly_name: "Toilet"
    light.toilet_lights:
      <<: *customize
      friendly_name: "Toilet Lights"
      icon: mdi:lightbulb
    group.toilet_switches:
      <<: *customize
      friendly_name: "Toilet Switches"
    sensor.toilet_temperature:
      <<: *customize
      friendly_name: "Toilet Temperature"
      icon: mdi:thermometer-lines
      unit_of_measurement: '°C'
    sensor.toilet_humidity:
      <<: *customize
      friendly_name: "Toilet Humidity"
      unit_of_measurement: '%'
    binary_sensor.toilet_occupancy:
      <<: *customize
      friendly_name: "Toilet Occupancy"
    binary_sensor.toilet_door:
      <<: *customize
      friendly_name: "Toilet Door"
    binary_sensor.toilet_window:
      <<: *customize
      friendly_name: "Toilet Window"
    switch.toilet_switch:
      <<: *customize
      friendly_name: "Toilet Switch"
    light.toilet_light:
      <<: *customize
      friendly_name: "Toilet Light"

group:
  toilet:
    control: hidden
    entities:
      - sensor.toilet_temperature
      - sensor.toilet_humidity
      - binary_sensor.toilet_occupancy
      - binary_sensor.toilet_door
      - binary_sensor.toilet_window
      - group.toilet_switches
      - light.toilet_lights
  toilet_switches:
    entities:
      - switch.toilet_switch
sensor:
  - platform: template
    sensors:
      toilet_temperature:
        value_template: '{{states.sensor.template.state}}'
      toilet_humidity:
        value_template: '{{states.sensor.template.state}}'

binary_sensor:
  - platform: template
    sensors:
      toilet_occupancy:
        value_template: "{{ is_state('binary_sensor.template', 'on')}}"
        device_class: occupancy
      toilet_door:
        value_template: "{{ is_state('binary_sensor.template', 'on')}}"
        device_class: door
      toilet_window:
        value_template: "{{ is_state('binary_sensor.template', 'on')}}"
        device_class: window

switch:
  - platform: template
    switches:
      toilet_switch:
        value_template: "{{ is_state('switch.template', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.template
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.template

light:
  - platform: template
    lights:
      toilet_light:
        value_template: "{{ is_state('light.template', 'on') }}"
        turn_on:
          service: light.turn_on
          data:
            entity_id: light.template
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.template
  - platform: group
    name: Toilet lights
    entities:
      - light.toilet_light
