- platform: mqtt
  state_topic: 'hass/loftpi/sensor/weatherstation_temperature/state'
  name: 'Outside Temperature'
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"
- platform: mqtt
  state_topic: 'hass/loftpi/sensor/weatherstation_humidity/state'
  name: 'Outside Humidity'
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
- platform: mqtt
  state_topic: 'hass/loftpi/sensor/weatherstation_wind_direction/state'
  name: 'Wind Direction'
- platform: mqtt
  state_topic: 'hass/loftpi/sensor/weatherstation_wind_speed/state'
  name: 'Wind Speed'
  unit_of_measurement: "kph"
- platform: mqtt
  state_topic: 'hass/loftpi/sensor/weatherstation_wind_gust/state'
  name: 'Wind Gust Speed'
  unit_of_measurement: "kph"
- platform: mqtt
  state_topic: 'hass/loftpi/sensor/weatherstation_rain_total/state'
  name: 'Total Rain Fall'
  unit_of_measurement: "mm"
- platform: mqtt
  state_topic: 'hass/loftpi/sensor/weatherstation_battery'
  name: 'Weather station battery'
  icon: "mdi:battery"

