# ninja blocks WT450 temp / humidity sensor #1
- platform: mqtt
  state_topic: 'RF/DKW2012-ID=0004'
  name: 'Outside Temperature'
  unit_of_measurement: "°C"
  value_template: '{{ value_json.TEMP }}'

- platform: mqtt
  state_topic: 'RF/DKW2012-ID=0004'
  name: 'Outside Humidity'
  unit_of_measurement: "%"
  value_template: '{{ value_json.HUM }}'

- platform: mqtt
  state_topic: 'RF/DKW2012-ID=0004'
  name: 'Wind Direction'
  value_template: '{{ value_json.WINDIR }}'

- platform: mqtt
  state_topic: 'RF/DKW2012-ID=0004'
  name: 'Wind Speed'
  unit_of_measurement: "kph"
  value_template: '{{ value_json.WINSP }}'

- platform: mqtt
  state_topic: 'RF/DKW2012-ID=0004'
  name: 'Wind Gust Speed'
  unit_of_measurement: "kph"
  value_template: '{{ value_json.WINGS }}'

- platform: mqtt
  state_topic: 'RF/DKW2012-ID=0004'
  name: 'Rain Fall'
  unit_of_measurement: "mm"
  value_template: '{{ value_json.RAIN }}'