- alias: Firestick Livingroom - Start Kodi
  trigger:
    platform: state
    entity_id: media_player.living_room_firestick
    to: 'off'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.kindle6a36ac6e8homelocal
      to: 'home'
    - condition: state
      entity_id: media_player.living_room_firestick
      to: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0
  action:
    - service: shell_command.firestick_kodi_livingroom_start
    - service: notify.slack
      data:
        message: 'Kodi is DOWN on Living room Firestick, Starting Kodi'
