- alias: Firestick Bedroom - Start Kodi
  trigger:
    - platform: state
      entity_id: media_player.bedroom_firestick
      state: off
  condition:
    entity_id: device_tracker.ac63be3a9c98
    state: home
    for:
      hours: 0
      minutes: 30
      seconds: 0
  action:
    - service: shell_command.firestick_kodi_bedroom_start
      delay:
        minutes: 5
    - service: notify.slack
        data:
        message: 'Kodi is DOWN on Bedroom Firestick, Starting Kodi'
- alias: Firestick Livingroom - Start Kodi
  trigger:
    - platform: state
      entity_id: media_player.living_room_firestick
      state: off
  condition:
    entity_id: device_tracker.kindle6a36ac6e8homelocal
    state: home
    for:
      hours: 0
      minutes: 30
      seconds: 0
  action:
    - service: shell_command.firestick_kodi_livingroom_start
      delay:
        minutes: 5
    - service: notify.slack
        data:
        message: 'Kodi is DOWN on room Firestick, Starting Kodi'
- alias: Firestick Kitchen - Start Kodi
  trigger:
    - platform: state
      entity_id: media_player.kitchen_firestick
      state: off
  condition:
    entity_id: device_tracker.kindlea0c9dd832homelocal
    state: home
    for:
      hours: 0
      minutes: 30
      seconds: 0
  action:
    - service: shell_command.firestick_kodi_kitchen_start
      delay:
        minutes: 5
    - service: notify.slack
        data:
        message: 'Kodi is DOWN on Kitchen Firestick, Starting Kodi'