- alias: Firestick Bedroom - Start Kodi
  trigger:
    platform: state
    entity_id: media_player.bedroom_firestick
    state: 'off'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.ac63be3a9c98
      state: 'home'
    - condition: state
      entity_id: media_player.bedroom_firestick
      state: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0
  action:
    - service: shell_command.firestick_kodi_bedroom_start
    - service: notify.slack
      data:
        message: 'Kodi is DOWN on Bedroom Firestick, Starting Kodi'