- alias: Stop Streaming Radio
  trigger:
    - platform: state
      entity_id: input_select.radio_station
      to: "None"
  action:
    service: media_player.turn_off
    data_template:
      entity_id: >
          {% if is_state("input_select.radio_player", "Living Room OSMC") %}
            media_player.livingroom_osmc
          {%-elif is_state("input_select.radio_player", "Living Room") %}
            media_player.living_room_firestick
          {%-elif is_state("input_select.radio_player", "Bedroom") %}
            media_player.bedroom_firestick
          {%-elif is_state("input_select.radio_player", "Kitchen") %}
            media_player.kitchen_firestick
          {% else %}
            none
          {% endif %}