- alias: Stream Radio - Template
  trigger:
    - platform: state
      entity_id: input_select.radio_station
  action:
    - service: media_player.play_media
      data_template:
        entity_id: >
          {% if is_state("input_select.radio_player", "Living Room OSMC") %}
            media_player.livingroom_osmc
          {%-elif is_state("input_select.radio_player", "Living Room") %}
            media_player.living_room_firestick
          {%-elif is_state("input_select.radio_player", "Bedroom") %}
            media_player.bedroom_firestick
          {%-elif is_state("input_select.radio_player", "Kitchen") %}
            media_player.kitchen_firestick
          {% else %}
            none
          {% endif %}
        media_content_id: >
          {% if is_state("input_select.radio_station", "Heart (Thames Valley)") %}
            http://media-ice.musicradio.com/HeartBerkshireMP3.m3u
          {%-elif is_state("input_select.radio_station", "Breeze Basingstoke") %}
            http://webradio.radiomonitor.com/m3u/Breeze-Basingstoke-128.m3u
          {% else %}
            none
          {% endif %}
        media_content_type: 'audio/mp4'