automation:
  - alias: Notify for new devices
    trigger:
      platform: event
      event_type: device_tracker_new_device
    action:
      - service: script.notify_me
        data: {"New device: {{trigger.event.data.host_name}} ({{trigger.event.data.entity_id}})"}
