homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'doors'

      exposed: &exposed
        <<: *customize
        emulated_hue: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false
      "binary_sensor.back_door":
        assumed_state: false
      "binary_sensor.front_door":
        assumed_state: false

binary_sensor:
  - platform: mqtt
    state_topic: 'hass/security/door/back'
    name: Back Door
    device_class: opening
    payload_on: "true"
    payload_off: "false"
  - platform: mqtt
    state_topic: 'hass/security/door/front'
    name: Front Door
    device_class: opening
    payload_on: "true"
    payload_off: "false"
