homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'doors'

      exposed: &exposed
        <<: *customize
        emulated_hue: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false
      "binary_sensor.back_door":
        assumed_state: false
      "binary_sensor.front_door":
        assumed_state: false

switch:
  - platform: rflink
    devices:
      byron_00ff_01:
        name: Front Door Bell
      ev1527_0d97d0_0a:
        name: Front Door Open
        fire_event: true
      ev1527_0d97d0_0e:
        name: Front Door Closed
        fire_event: true
      ev1527_0b0aa0_0a:
        name: Back Door Open
        fire_event: true
        aliases:
          - selectplus_07aafa_02
      ev1527_0b0aa0_0e:
        name: Back Door Closed
        fire_event: true
        aliases:
          - selectplus_07aaf8_02
binary_sensor:
  - platform: mqtt
    state_topic: 'hass/security/door/back'
    name: Back Door
    device_class: opening
    payload_on: "true"
    payload_off: "false"
  - platform: mqtt
    state_topic: 'hass/security/door/front'
    name: Front Door
    device_class: opening
    payload_on: "true"
    payload_off: "false"
automation:
  - id: resetbackdoorsopenonstartup
    alias: 'Reset Opened Back Door on startup'
    initial_state: 'on'
    trigger:
     - platform: homeassistant
       event: start
    condition:
    - condition: template
      value_template:  >-
        {{ states.binary_sensor.back_door.state == 'on' }}
    action:
    - service: switch.turn_on
      entity_id: switch.back_door_open
    - service: switch.turn_off
      entity_id: switch.back_door_closed
  - id: resetbackdoorsclosedonstartup
    alias: 'Reset Closed Back Door on startup'
    initial_state: 'on'
    trigger:
     - platform: homeassistant
       event: start
    condition:
    - condition: template
      value_template:  >-
        {{ states.binary_sensor.back_door.state == 'off' }}
    action:
    - service: switch.turn_off
      entity_id: switch.back_door_open
    - service: switch.turn_on
      entity_id: switch.back_door_closed
  - id: resetfrontdoorsopenonstartup
    alias: 'Reset Opened Front Door on startup'
    initial_state: 'on'
    trigger:
     - platform: homeassistant
       event: start
    condition:
    - condition: template
      value_template:  >-
        {{ states.binary_sensor.front_door.state == 'on' }}
    action:
    - service: switch.turn_on
      entity_id: switch.front_door_open
    - service: switch.turn_off
      entity_id: switch.front_door_closed
  - id: resetfrontdoorsclosedonstartup
    alias: 'Reset Closed front Door on startup'
    initial_state: 'on'
    trigger:
     - platform: homeassistant
       event: start
    condition:
    - condition: template
      value_template:  >-
        {{ states.binary_sensor.front_door.state == 'off' }}
    action:
    - service: switch.turn_off
      entity_id: switch.front_door_open
    - service: switch.turn_on
      entity_id: switch.front_door_closed
  - id: 'backdooropen'
    alias: back door open
    initial_state: 'on'
    trigger:
    - entity_id: switch.back_door_open
      from: 'off'
      platform: state
      to: 'on'
    condition: []
    action:
    - data:
        entity_id: switch.back_door_closed
      service: switch.turn_off
    - data:
        payload: 'true'
        qos: 2
        retain: true
        topic: hass/security/door/back
      service: mqtt.publish
  - id: 'backdoorclosed'
    alias: back door closed
    initial_state: 'on'
    trigger:
    - entity_id: switch.back_door_closed
      from: 'off'
      platform: state
      to: 'on'
    condition: []
    action:
    - data:
        entity_id: switch.back_door_open
      service: switch.turn_off
    - data:
        payload: 'false'
        qos: 2
        retain: true
        topic: hass/security/door/back
      service: mqtt.publish
  - id: 'frontdooropen'
    alias: front door open
    initial_state: 'on'
    trigger:
    - entity_id: switch.front_door_open
      from: 'off'
      platform: state
      to: 'on'
    condition: []
    action:
    - data:
        entity_id: switch.front_door_closed
      service: switch.turn_off
    - data:
        payload: 'true'
        qos: 2
        retain: true
        topic: hass/security/door/front
      service: mqtt.publish
  - id: 'frontdoorclosed'
    alias: front door closed
    initial_state: 'on'
    trigger:
    - entity_id: switch.front_door_closed
      from: 'off'
      platform: state
      to: 'on'
    condition: []
    action:
    - data:
        entity_id: switch.front_door_open
      service: switch.turn_off
    - data:
        payload: 'false'
        qos: 2
        retain: true
        topic: hass/security/door/front
      service: mqtt.publish

