binary_sensor:
  - platform: mqtt
    name: "Front Door"
    state_topic: "hass/loftpi/binary_sensor/front_door/state"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: opening
  - platform: mqtt
    name: "Back Door"
    state_topic: "hass/loftpi/binary_sensor/back_door/state"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: opening