################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'heating'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.immersion:
      <<: *customize
      friendly_name: "Immersion"
      icon: mdi:steam
group:
  immersion:
    control: hidden
    entities:
      - sensor.immersion_heater_voltage
      - sensor.immersion_heater_amperage
      - sensor.immersion_heater_watts
      - sensor.immersion_heater_today
      - sensor.immersion_heater_yesterday
      - sensor.immersion_heater_total
      - switch.immersion_heater
sensor:
  - platform: mqtt
    name: 'Immersion Heater Voltage'
    state_topic: 'tele/immersion/ENERGY'
    value_template: '{{ value_json.Voltage }}'
    unit_of_measurement: 'v'
  - platform: mqtt
    name: 'Immersion Heater Amperage'
    state_topic: 'tele/immersion/ENERGY'
    value_template: '{{ value_json.Current }}'
    unit_of_measurement: 'A'
  - platform: mqtt
    name: 'Immersion Heater Watts'
    state_topic: 'tele/immersion/ENERGY'
    value_template: '{{ value_json.Power }}'
    unit_of_measurement: 'watts'
  - platform: mqtt
    name: 'Immersion Heater Today'
    state_topic: 'tele/immersion/ENERGY'
    value_template: '{{ value_json.Today }}'
    unit_of_measurement: 'kw'
  - platform: mqtt
    name: 'Immersion Heater Yesterday'
    state_topic: 'tele/immersion/ENERGY'
    value_template: '{{ value_json.Yesterday }}'
    unit_of_measurement: 'kw'
  - platform: mqtt
    name: 'Immersion Heater Total'
    state_topic: 'tele/immersion/ENERGY'
    value_template: '{{ value_json.Total }}'
    unit_of_measurement: 'kw'
switch:
  - platform: mqtt
    name: 'Immersion Heater'
    command_topic: 'cmnd/immersion/POWER'
    state_topic: 'stat/immersion/POWER'
#    availability_topic: 'tele/immersion/LWT'
#    value_template: '{{ value_json.POWER }}'
#    payload_available: 'ONLINE'
#    payload_not_available: 'OFFLINE'
