sensor:
  - platform: mqtt
    state_topic: "wallpanel/mywallpanel/sensor/battery"
    name: "wallpanel battery"
    unit_of_measurement: "%"
    value_template: '{{ value_json.value }}'

binary_sensor:
  - platform: mqtt
    state_topic: "wallpanel/mywallpanel/sensor/motion"
    name: "WallPanel Motion"
    payload_on: '{"value":true}'
    payload_off: '{"value":false}'
    device_class: motion
